#!/bin/bash

# This script is intended to be called by ControlPlane when in "Desktop" context which fixes key mappings for external
# mechanical keyboards. It maps keys natively via hidutil so we don't have to use Karabiner Elements which always breaks
# for us. Use https://hidutil-generator.netlify.app to help generate these mappings
#
# The following mappings correspond to:
# 1. caps_lock -> f18
# 2. left_option -> left_command
# 3. left_command -> left_option
# 4. right_option -> right_command
# 5. right_command -> right_option
# 6. f7 -> rewind
# 7. f8 -> play_or_pause
# 8. f9 -> fast_forward
# 9. f10 -> mute
# 10. f11 -> volume_decrement
# 11. f12 -> volume_increment
hidutil property --set \
'{
  "UserKeyMapping": [
    {
      "HIDKeyboardModifierMappingSrc": 0x700000039,
      "HIDKeyboardModifierMappingDst": 0x70000006D
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x7000000E2,
      "HIDKeyboardModifierMappingDst": 0x7000000E3
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x7000000E3,
      "HIDKeyboardModifierMappingDst": 0x7000000E2
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x7000000E6,
      "HIDKeyboardModifierMappingDst": 0x7000000E7
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x7000000E7,
      "HIDKeyboardModifierMappingDst": 0x7000000E6
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x700000040,
      "HIDKeyboardModifierMappingDst": 0xC000000B4
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x700000041,
      "HIDKeyboardModifierMappingDst": 0xC000000CD
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x700000042,
      "HIDKeyboardModifierMappingDst": 0xC000000B3
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x700000043,
      "HIDKeyboardModifierMappingDst": 0xC000000E2
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x700000044,
      "HIDKeyboardModifierMappingDst": 0xC000000EA
    },
    {
      "HIDKeyboardModifierMappingSrc": 0x700000045,
      "HIDKeyboardModifierMappingDst": 0xC000000E9
    }
]
}'

exit 0
