#!/usr/bin/env ruby

require 'json'

new_profile = ARGV[0]

karabiner_path = File.expand_path(File.dirname(__FILE__))
karabiner_config_path = "#{karabiner_path}/karabiner.json"

karabiner_config = JSON.parse(File.open(karabiner_config_path).read)

profiles = []

karabiner_config['profiles'].each do |profile|
  profile['selected'] = (new_profile == profile['name']) ? true : false 

  profiles << profile
end

karabiner_config['profiles'] = profiles

File.open(karabiner_config_path, 'w') { |f| f.write(JSON.pretty_generate(karabiner_config)) }

system "killall karabiner_console_user_server" 
